<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Agendar Consulta - Dra. Daniela Lima</title>
    <link rel="stylesheet" href="assets/css/style.css">
</head>
<body>
    <header class="header">
        <div class="container">
            <div class="header-content">
                <a href="index.php" class="logo">Terapia e Bem Estar</a>
                <nav class="nav">
                    <a href="index.php">Início</a>
                    <a href="index.php?page=services">Serviços</a>
                    <a href="index.php?page=calendar" class="active">Agendar</a>
                    <a href="index.php?page=google_meet_tutorial">Primeira Consulta</a>
                </nav>
            </div>
        </div>
    </header>

    <main class="main">
        <div class="container">
            <?php
            global $pdo;
            $selected_date = $_GET['date'] ?? null;
            $selected_time = $_GET['time'] ?? null;
            ?>

            <section class="hero">
                <h1>Agenda Online</h1>
                <p class="subtitle">Agende sua consulta psicológica online de forma simples e rápida</p>
            </section>

            <div style="display: grid; grid-template-columns: 1fr; gap: 2rem;">
                <!-- Step 1: Choose Date -->
                <section class="card">
                    <h2 style="color: var(--primary-color); margin-bottom: 1rem;">1. Escolha a Data</h2>
                    <p style="margin-bottom: 2rem; color: var(--text-light);">Selecione uma data disponível para sua consulta:</p>
                    <div id="calendar-container">
                        <!-- Calendar will be generated by JavaScript -->
                    </div>
                </section>
                
                <!-- Step 2: Choose Time -->
                <?php if ($selected_date): ?>
                <section class="card">
                    <h2 style="color: var(--primary-color); margin-bottom: 1rem;">2. Escolha o Horário</h2>
                    <p style="margin-bottom: 2rem; color: var(--text-light);">Horários disponíveis para <?= date('d/m/Y', strtotime($selected_date)) ?>:</p>
                    <div id="time-slots-container">
                        <?php
                        // Get available time slots for the selected date
                        if (isset($pdo)) {
                        try {
                            $stmt = $pdo->prepare("
                                SELECT t.time 
                                FROM time_slots t 
                                LEFT JOIN appointments a ON t.date = a.appointment_date AND t.time = a.appointment_time AND a.status != 'cancelled'
                                WHERE t.date = ? AND t.is_available = true AND a.id IS NULL
                                ORDER BY t.time ASC
                            ");
                            $stmt->execute([$selected_date]);
                            $available_times = $stmt->fetchAll(PDO::FETCH_COLUMN);
                            
                            if (count($available_times) > 0): 
                                // Organize times by period
                                $morning = [];
                                $afternoon = [];
                                $evening = [];
                                
                                foreach($available_times as $time) {
                                    $hour = (int)date('H', strtotime($time));
                                    if ($hour < 12) {
                                        $morning[] = $time;
                                    } elseif ($hour < 18) {
                                        $afternoon[] = $time;
                                    } else {
                                        $evening[] = $time;
                                    }
                                }
                                ?>
                                <div class="time-periods">
                                    <?php if (!empty($morning)): ?>
                                        <div class="time-period">
                                            <h4>🌅 Manhã</h4>
                                            <div class="time-slots">
                                                <?php foreach($morning as $time): ?>
                                                    <div class="time-slot <?= $selected_time == $time ? 'selected' : '' ?>" 
                                                         onclick="selectTime('<?= $time ?>')">
                                                        <?= date('H:i', strtotime($time)) ?>
                                                    </div>
                                                <?php endforeach; ?>
                                            </div>
                                        </div>
                                    <?php endif; ?>
                                    
                                    <?php if (!empty($afternoon)): ?>
                                        <div class="time-period">
                                            <h4>☀️ Tarde</h4>
                                            <div class="time-slots">
                                                <?php foreach($afternoon as $time): ?>
                                                    <div class="time-slot <?= $selected_time == $time ? 'selected' : '' ?>" 
                                                         onclick="selectTime('<?= $time ?>')">
                                                        <?= date('H:i', strtotime($time)) ?>
                                                    </div>
                                                <?php endforeach; ?>
                                            </div>
                                        </div>
                                    <?php endif; ?>
                                    
                                    <?php if (!empty($evening)): ?>
                                        <div class="time-period">
                                            <h4>🌙 Noite</h4>
                                            <div class="time-slots">
                                                <?php foreach($evening as $time): ?>
                                                    <div class="time-slot <?= $selected_time == $time ? 'selected' : '' ?>" 
                                                         onclick="selectTime('<?= $time ?>')">
                                                        <?= date('H:i', strtotime($time)) ?>
                                                    </div>
                                                <?php endforeach; ?>
                                            </div>
                                        </div>
                                    <?php endif; ?>
                                </div>
                                
                                <?php if ($selected_time): ?>
                                    <div class="mt-2 text-center">
                                        <a href="index.php?page=booking&date=<?= urlencode($selected_date) ?>&time=<?= urlencode($selected_time) ?><?= isset($_GET['service_id']) ? '&service_id=' . urlencode($_GET['service_id']) : '' ?>" 
                                           class="btn btn-large">Continuar para Dados Pessoais</a>
                                    </div>
                                <?php endif; ?>
                            <?php else: ?>
                                <p>Não há horários disponíveis para esta data. Por favor, escolha outra data.</p>
                            <?php endif;
                        } catch(PDOException $e) {
                            echo '<p>Erro ao carregar horários disponíveis.</p>';
                        }
                        } else {
                            echo '<p>Erro de conexão com banco de dados.</p>';
                        }
                        ?>
                    </div>
                </section>
                <?php endif; ?>
            </div>
        </div>
    </main>

    <footer class="footer">
        <div class="container">
            <p>&copy; 2024 Terapia e Bem Estar - Dra. Daniela Lima. Todos os direitos reservados.</p>
            <p>CRP 00000/00 | Atendimento psicológico online</p>
        </div>
    </footer>

    <script>
        // Calendar functionality
        let currentMonth = new Date().getMonth();
        let currentYear = new Date().getFullYear();
        
        document.addEventListener('DOMContentLoaded', function() {
            // Initialize calendar
            generateCalendar();
        });
        
        function generateCalendar() {
            const container = document.getElementById('calendar-container');
            if (!container) return;
            
            const today = new Date();
            
            let calendarHTML = `
                <div class="calendar">
                    <div class="calendar-header">
                        <button class="calendar-nav" onclick="changeMonth(-1)">&lt;</button>
                        <h3 id="month-year">${getMonthName(currentMonth)} ${currentYear}</h3>
                        <button class="calendar-nav" onclick="changeMonth(1)">&gt;</button>
                    </div>
                    <div class="calendar-grid">
                        <div style="font-weight: bold; background: var(--primary-color); color: white; padding: 0.5rem;">Dom</div>
                        <div style="font-weight: bold; background: var(--primary-color); color: white; padding: 0.5rem;">Seg</div>
                        <div style="font-weight: bold; background: var(--primary-color); color: white; padding: 0.5rem;">Ter</div>
                        <div style="font-weight: bold; background: var(--primary-color); color: white; padding: 0.5rem;">Qua</div>
                        <div style="font-weight: bold; background: var(--primary-color); color: white; padding: 0.5rem;">Qui</div>
                        <div style="font-weight: bold; background: var(--primary-color); color: white; padding: 0.5rem;">Sex</div>
                        <div style="font-weight: bold; background: var(--primary-color); color: white; padding: 0.5rem;">Sáb</div>
            `;
            
            // Generate calendar days
            const firstDay = new Date(currentYear, currentMonth, 1);
            const lastDay = new Date(currentYear, currentMonth + 1, 0);
            const startDate = new Date(firstDay);
            startDate.setDate(startDate.getDate() - firstDay.getDay());
            
            for (let i = 0; i < 42; i++) {
                const date = new Date(startDate);
                date.setDate(startDate.getDate() + i);
                
                const isCurrentMonth = date.getMonth() === currentMonth;
                const isPast = date < today.setHours(0,0,0,0);
                const isWeekend = date.getDay() === 0 || date.getDay() === 6;
                const dateStr = date.toISOString().split('T')[0];
                
                let classes = 'calendar-day';
                if (!isCurrentMonth) classes += ' text-light';
                if (isPast || isWeekend) classes += ' unavailable';
                if (<?= json_encode($selected_date ?? '') ?> === dateStr) classes += ' selected';
                
                const clickable = isCurrentMonth && !isPast && !isWeekend;
                
                calendarHTML += `
                    <div class="${classes}" ${clickable ? `onclick="selectDate('${dateStr}')"` : ''}>
                        ${date.getDate()}
                    </div>
                `;
            }
            
            calendarHTML += '</div></div>';
            container.innerHTML = calendarHTML;
        }
        
        function getMonthName(month) {
            const months = ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho',
                          'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'];
            return months[month];
        }
        
        function selectDate(date) {
            // Debug log
            console.log('selectDate chamada com:', date);
            
            // Preserve existing query parameters (like service_id)
            const urlParams = new URLSearchParams(window.location.search);
            urlParams.set('page', 'calendar');
            urlParams.set('date', date);
            urlParams.delete('time'); // Reset time when selecting new date
            
            // Build absolute URL
            const newUrl = window.location.origin + window.location.pathname + '?' + urlParams.toString();
            console.log('Redirecionando para:', newUrl);
            
            window.location.href = newUrl;
        }
        
        function changeMonth(direction) {
            currentMonth += direction;
            if (currentMonth > 11) {
                currentMonth = 0;
                currentYear++;
            } else if (currentMonth < 0) {
                currentMonth = 11;
                currentYear--;
            }
            generateCalendar();
        }
        
        function selectTime(time) {
            // Get date from PHP or from current URL
            let date = <?= json_encode($selected_date ?? '') ?>;
            
            // If no date from PHP, try to get from current URL
            if (!date) {
                const urlParams = new URLSearchParams(window.location.search);
                date = urlParams.get('date');
            }
            
            if (date) {
                // Debug log
                console.log('selectTime chamada com:', time, 'data:', date);
                
                // Preserve existing query parameters (like service_id)
                const urlParams = new URLSearchParams(window.location.search);
                urlParams.set('page', 'calendar');
                urlParams.set('date', date);
                urlParams.set('time', time);
                
                // Build absolute URL
                const newUrl = window.location.origin + window.location.pathname + '?' + urlParams.toString();
                console.log('Redirecionando para:', newUrl);
                
                window.location.href = newUrl;
            } else {
                console.error('Nenhuma data selecionada para escolher horário');
                alert('Por favor, selecione uma data primeiro.');
            }
        }
    </script>
</body>
</html>