<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Agendar Consulta - Dra. Daniela Lima</title>
    <link rel="stylesheet" href="assets/css/style.css">
</head>
<body>
    <header class="header">
        <div class="container">
            <div class="header-content">
                <a href="index.php" class="logo"><img src="assets/images/logo-dra-daniela.png" alt="Dra. Daniela Lima - Psicóloga"></a>
                <nav class="nav">
                    <a href="index.php">Início</a>
                    <a href="index.php?page=services">Serviços</a>
                    <a href="index.php?page=calendar" class="active">Agendar</a>
                    <a href="index.php?page=google_meet_tutorial">Primeira Consulta</a>
                </nav>
            </div>
        </div>
    </header>

    <main class="main">
        <div class="container">
            <?php
            global $pdo;
            $selected_date = $_GET['date'] ?? null;
            $selected_time = $_GET['time'] ?? null;
            ?>

            <!-- Progress Indicator -->
            <div class="progress-indicator">
                <div class="progress-steps">
                    <div class="progress-track"></div>
                    <div class="progress-step active">
                        <div class="progress-number">1</div>
                        <span class="progress-label">Encontre Seu Horário</span>
                    </div>
                    <div class="progress-step">
                        <div class="progress-number">2</div>
                        <span class="progress-label">Seus Dados</span>
                    </div>
                    <div class="progress-step">
                        <div class="progress-number">3</div>
                        <span class="progress-label">Revisão</span>
                    </div>
                </div>
            </div>

            <section class="hero">
                <h1 class="calendar-title">Escolha Data e Horário</h1>
                <p class="calendar-subtitle">
                    Selecione a data e o horário que melhor funcionam para você. É rápido e simples.
                </p>
                <div class="calendar-legend">
                    <div class="legend-item">
                        <div class="legend-color legend-color-available"></div>
                        <span>Verde = Disponível</span>
                    </div>
                    <div class="legend-item">
                        <div class="legend-color legend-color-free"></div>
                        <span>Azul = Horários Livres</span>
                    </div>
                    <div class="legend-item">
                        <div class="legend-color legend-color-unavailable"></div>
                        <span>Cinza = Indisponível</span>
                    </div>
                </div>
            </section>

            <div class="calendar-grid-2col">
                <!-- Left Column: Choose Date -->
                <section class="card">
                    <div class="card-header">
                        <h2 class="card-title">📅 Selecione a Data</h2>
                        <p class="card-description">
                            Clique em qualquer dia verde
                        </p>
                    </div>
                    <div id="calendar-container">
                        <!-- Calendar will be generated by JavaScript -->
                    </div>
                </section>
                
                <!-- Right Column: Choose Time -->
                <section class="card <?php if ($selected_date): ?>card-active<?php endif; ?>">
                    <div class="card-header">
                        <h2 class="card-title card-title-time">⏰ Selecione o Horário</h2>
                        <?php if ($selected_date): ?>
                            <div class="selected-date-box">
                                <p>
                                    <strong><?= date('d/m/Y', strtotime($selected_date)) ?></strong>
                                </p>
                            </div>
                            <p class="card-description">
                                Clique em um horário azul disponível
                            </p>
                        <?php else: ?>
                            <p class="card-description">
                                Primeiro selecione uma data ao lado
                            </p>
                        <?php endif; ?>
                    </div>
                    <div id="time-slots-container">
                        <?php
                        // Only show time slots if a date is selected
                        if ($selected_date && isset($pdo)) {
                        try {
                            $stmt = $pdo->prepare("
                                SELECT t.time 
                                FROM time_slots t 
                                LEFT JOIN appointments a ON t.date = a.appointment_date AND t.time = a.appointment_time AND a.status != 'cancelled'
                                WHERE t.date = ? AND t.is_available = true AND a.id IS NULL
                                ORDER BY t.time ASC
                            ");
                            $stmt->execute([$selected_date]);
                            $available_times = $stmt->fetchAll(PDO::FETCH_COLUMN);
                            
                            if (count($available_times) > 0): 
                                // Organize times by period
                                $morning = [];
                                $afternoon = [];
                                $evening = [];
                                
                                foreach($available_times as $time) {
                                    $hour = (int)date('H', strtotime($time));
                                    if ($hour < 12) {
                                        $morning[] = $time;
                                    } elseif ($hour < 18) {
                                        $afternoon[] = $time;
                                    } else {
                                        $evening[] = $time;
                                    }
                                }
                                ?>
                                <div class="time-periods">
                                    <?php if (!empty($morning)): ?>
                                        <div class="time-period">
                                            <h4 class="time-period-title">🌅 Manhã</h4>
                                            <div class="time-slots">
                                                <?php foreach($morning as $time): ?>
                                                    <div class="time-slot <?= $selected_time == $time ? 'selected' : '' ?>" 
                                                         onclick="selectTime('<?= $time ?>')">
                                                        <?= date('H:i', strtotime($time)) ?>
                                                    </div>
                                                <?php endforeach; ?>
                                            </div>
                                        </div>
                                    <?php endif; ?>
                                    
                                    <?php if (!empty($afternoon)): ?>
                                        <div class="time-period">
                                            <h4 class="time-period-title">☀️ Tarde</h4>
                                            <div class="time-slots">
                                                <?php foreach($afternoon as $time): ?>
                                                    <div class="time-slot <?= $selected_time == $time ? 'selected' : '' ?>" 
                                                         onclick="selectTime('<?= $time ?>')">
                                                        <?= date('H:i', strtotime($time)) ?>
                                                    </div>
                                                <?php endforeach; ?>
                                            </div>
                                        </div>
                                    <?php endif; ?>
                                    
                                    <?php if (!empty($evening)): ?>
                                        <div class="time-period">
                                            <h4 class="time-period-title">🌙 Noite</h4>
                                            <div class="time-slots">
                                                <?php foreach($evening as $time): ?>
                                                    <div class="time-slot <?= $selected_time == $time ? 'selected' : '' ?>" 
                                                         onclick="selectTime('<?= $time ?>')">
                                                        <?= date('H:i', strtotime($time)) ?>
                                                    </div>
                                                <?php endforeach; ?>
                                            </div>
                                        </div>
                                    <?php endif; ?>
                                </div>
                                
                                <?php if ($selected_time): ?>
                                    <div class="success-box">
                                        <div class="success-icon">
                                            <span>✓</span>
                                        </div>
                                        <h3 class="success-title">Perfeito!</h3>
                                        <p class="success-text">
                                            <strong><?= date('d/m/Y', strtotime($selected_date)) ?> às <?= date('H:i', strtotime($selected_time)) ?></strong>
                                        </p>
                                        <a href="index.php?page=booking&date=<?= urlencode($selected_date) ?>&time=<?= urlencode($selected_time) ?><?= isset($_GET['service_id']) ? '&service_id=' . urlencode($_GET['service_id']) : '' ?>" 
                                           class="btn btn-large btn-continue">
                                            Continuar →
                                        </a>
                                    </div>
                                <?php endif; ?>
                            <?php else: ?>
                                <div class="warning-box">
                                    <div class="warning-icon">📅</div>
                                    <p class="warning-title">Ops! Esta data está cheia</p>
                                    <p class="warning-text">Não se preocupe, escolha outra data verde no calendário acima.</p>
                                </div>
                            <?php endif;
                        } catch(PDOException $e) {
                            echo '<div class="error-box"><p>Erro ao carregar horários disponíveis.</p></div>';
                        }
                        } elseif (!$selected_date) {
                            // Show neutral prompt when no date is selected
                            echo '<div class="empty-state-box">
                                    <div class="empty-state-icon">📆</div>
                                    <p class="empty-state-title">Aguardando seleção de data</p>
                                    <p class="empty-state-text">Clique em um dia verde no calendário ao lado para ver os horários disponíveis</p>
                                </div>';
                        } else {
                            echo '<div class="error-box"><p>Erro de conexão com banco de dados.</p></div>';
                        }
                        ?>
                    </div>
                </section>
        </div>
    </main>

    <footer class="footer">
        <div class="container">
            <div class="logo-footer"><img src="assets/images/logo-dra-daniela.png" alt="Dra. Daniela Lima - Psicóloga"></div>
            <p>&copy; 2024 Terapia e Bem Estar - Dra. Daniela Lima. Todos os direitos reservados.</p>
            <p>CRP 00000/00 | Atendimento psicológico online</p>
        </div>
    </footer>

    <script>
        // Calendar functionality
        let currentMonth = new Date().getMonth();
        let currentYear = new Date().getFullYear();
        
        document.addEventListener('DOMContentLoaded', function() {
            // Initialize calendar
            generateCalendar();
        });
        
        function generateCalendar() {
            const container = document.getElementById('calendar-container');
            if (!container) return;
            
            const today = new Date();
            
            let calendarHTML = `
                <div class="calendar">
                    <div class="calendar-header">
                        <button class="calendar-nav" onclick="changeMonth(-1)">&lt;</button>
                        <h3 id="month-year" class="calendar-month-year">${getMonthName(currentMonth)} ${currentYear}</h3>
                        <button class="calendar-nav" onclick="changeMonth(1)">&gt;</button>
                    </div>
                    <div class="calendar-grid">
                        <div class="calendar-weekday">Dom</div>
                        <div class="calendar-weekday">Seg</div>
                        <div class="calendar-weekday">Ter</div>
                        <div class="calendar-weekday">Qua</div>
                        <div class="calendar-weekday">Qui</div>
                        <div class="calendar-weekday">Sex</div>
                        <div class="calendar-weekday">Sáb</div>
            `;
            
            // Generate calendar days
            const firstDay = new Date(currentYear, currentMonth, 1);
            const lastDay = new Date(currentYear, currentMonth + 1, 0);
            const startDate = new Date(firstDay);
            startDate.setDate(startDate.getDate() - firstDay.getDay());
            
            for (let i = 0; i < 42; i++) {
                const date = new Date(startDate);
                date.setDate(startDate.getDate() + i);
                
                const isCurrentMonth = date.getMonth() === currentMonth;
                const isPast = date < today.setHours(0,0,0,0);
                const isWeekend = date.getDay() === 0 || date.getDay() === 6;
                const dateStr = date.toISOString().split('T')[0];
                
                let classes = 'calendar-day';
                if (!isCurrentMonth) classes += ' text-light';
                if (isPast || isWeekend) classes += ' unavailable';
                if (<?= json_encode($selected_date ?? '') ?> === dateStr) classes += ' selected';
                
                const clickable = isCurrentMonth && !isPast && !isWeekend;
                
                calendarHTML += `
                    <div class="${classes}" ${clickable ? `onclick="selectDate('${dateStr}')"` : ''}>
                        ${date.getDate()}
                    </div>
                `;
            }
            
            calendarHTML += '</div></div>';
            container.innerHTML = calendarHTML;
        }
        
        function getMonthName(month) {
            const months = ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho',
                          'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'];
            return months[month];
        }
        
        function selectDate(date) {
            // Preserve existing query parameters (like service_id)
            const urlParams = new URLSearchParams(window.location.search);
            urlParams.set('page', 'calendar');
            urlParams.set('date', date);
            urlParams.delete('time'); // Reset time when selecting new date
            
            // Build absolute URL
            const newUrl = window.location.origin + window.location.pathname + '?' + urlParams.toString();
            window.location.href = newUrl;
        }
        
        function changeMonth(direction) {
            currentMonth += direction;
            if (currentMonth > 11) {
                currentMonth = 0;
                currentYear++;
            } else if (currentMonth < 0) {
                currentMonth = 11;
                currentYear--;
            }
            generateCalendar();
        }
        
        function selectTime(time) {
            // Get date from PHP or from current URL
            let date = <?= json_encode($selected_date ?? '') ?>;
            
            // If no date from PHP, try to get from current URL
            if (!date) {
                const urlParams = new URLSearchParams(window.location.search);
                date = urlParams.get('date');
            }
            
            if (date) {
                // Preserve existing query parameters (like service_id)
                const urlParams = new URLSearchParams(window.location.search);
                urlParams.set('page', 'calendar');
                urlParams.set('date', date);
                urlParams.set('time', time);
                
                // Build absolute URL
                const newUrl = window.location.origin + window.location.pathname + '?' + urlParams.toString();
                window.location.href = newUrl;
            } else {
                console.error('Nenhuma data selecionada para escolher horário');
                alert('Por favor, selecione uma data primeiro.');
            }
        }
    </script>
</body>
</html>
